Make changes to Crooks Peak
Charlesworth/crooksPeakWebsite pull request #1
Opened 2021-11-01 17:28 UTC by a-jennings

### Evening Charlie
Decided to have some fun this afternoon and make some changes to your Crooks Peak page. Let me know if you like them!
Page is response, has all the info from the Alien Extraction press pack and I know you're busy actually coding the game ;)

Have fun!

![chrome-capture](https://user-images.githubusercontent.com/16850455/139713621-3d36daad-1458-47bf-9f3d-e20a959988a4.jpg)

2021-11-03 11:16 UTC, Charlesworth requested changes
Looks great, a few change requests:
- If you add an external tool (SASS), add a README.md with the instruction on how to use the  tool (i.e. "$ sass <input.sass> <output.css>" or "$ node run <cmd>")
- Get rid of google fonts
- At some view port sizes (1000x1200) the footer hovers up from the bottom of the page, may be a problem with your "@media (max-width:" stuff
- Can you make the "Available March 2022" a link to "alienextraction.com"

2021-11-03 11:16 UTC, Charlesworth commented on index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
As a performance hound and privacy advocate, I usually like to not use 3rd party hosted fonts, can you either have a local copy of the font (make sure to check font licensing for this) or use system fonts.

2021-11-03 11:16 UTC, Charlesworth commented on sass/base/_reset.scss
> +      font-family: 'Lato', sans-serif;
Re 3rd party fonts comment

2021-11-03 11:19 UTC, Charlesworth commented
@a-jennings didn't like the emoji rain? 😆

2021-11-03 16:14 UTC, a-jennings commented
![chrome-capture (1)](https://user-images.githubusercontent.com/16850455/140098644-dcfd1dd0-c6fb-4bd0-ac7d-a70da951e245.gif)

- New font added to page
- AE-wide image converted to webp:  242k ->  14k
- Use only short game description instead of wall of text
- Change bright color scheme to darker and add animated stars in background (They're much better than the gif shows)

2021-11-04 20:43 UTC, Charlesworth approved these changes
great job, I'll put it live now, cheers buddy

2021-11-04 20:44 UTC, merged